### ISSUE TITLE
To do before merging optimizations into master

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#218]
- [x] Timing of intro sequence
- [x] Timing of all transitions from overworld to battle
- [x] Red, Green, and maybe other NPCs face away after their `showtextfaceplayer` textbox closes before battle begins
- [x] Pressing B to exit the Bag or party makes two beeping noises; the Pokédex and Pokégear correctly make one
- [ ] Timing of Surf move animation (not essential)

**Comment by FredrIQ** [comment]
7db832668d610ab5609fa18d9358f0817981f76d addresses the obvious menu sound effect issues. The problem is that performance improvements has resulted in certain transistions outpacing the menu click sound.

Various code, both vanilla and performance-boosted, disables interrupts (or, in at least one case I know of, pauses sound effects), pausing sound effects. This is what is happening.

I inserted case-by-case delays. The reason I didn't use WaitSFX is simple: it generally demanded a noticeably longer delay than the alternative, and you still have to add them on a case-per-case basis anyway.

**Comment by Rangi42** [comment]
Thanks. I agree; the Start menu is used often enough for those two audio glitches to stand out, but any others are not a major issue. Once `showtextfaceplayer` behaves this can be merged!

**Comment by FredrIQ** [comment]
493276b fixes all NPC facing bugs, but might have unintentional side effects. Going to do a playthrough with it.

It also makes the step_end/step_resume split obsolete (and the commit makes new step_end dead code so things can be properly tested), so if the commit truly doesn't have any bad side effects, scripts can be reverted to how they used to be beforehand.
