### ISSUE TITLE
(Possibly random) Crash on Cianwood Gym trainer battle

### ISSUE THREAD

**Issue by BlazeElPadrino** [Rangi42/polishedcrystal#252]
The battle where issue #251 happens also leads to a suspected random crash. https://youtu.be/qdFw8e3WFCw

**Comment by itsdarsh** [comment]
Not able to replicate this, despite my attempt to match this video as much as possible (i.e. using a Lv 30 Togetic with the same moves and HP and nickname and even using hacks to have the opponent use moves in the same order as in the video). The main suspicion I have is that it's related to critical hits, but hacking in a crit for the last move when the crash should've occurred didn't produce results either. It's possible that this crash is caused by something I didn't account for in my hacking but ordinary battling this trainer with Togetic wasn't any more fruitful. Due to the age of this issue, unless someone else produces a similar outcome it can probably be listed as unconfirmed.

**Comment by Rangi42** [comment]
This can be reopened if it happens again with a more recent build.
