### ISSUE TITLE
Stat calculations based on perfect DVs depending on EV bits

### ISSUE THREAD

**Issue by itsdarsh** [Rangi42/polishedcrystal#272]
When Pokemon stats are calculated via CalcPkmnStats (found in engine/move_mon.asm), a pokemon will have their stats based on perfect DVs for a single stat depending on the following conditions:

- For HP, if bit 7 of Pokemon's HP EV is set (i.e. HPEV = 128, or 10000000b)
- For Attack, if bit 6 of Pokemon's attack EV is set (i.e. AtkEV = 64, or 01000000b)
- For Defense, if bit 5 of Pokemon's defense EV is set (i.e. DefEV = 32, or 00100000b)

And so on.

This actually means that any Pokemon with max EVs in a stat (252, or 11111100b) will essentially have max DVs as well for that stat. I suspect this bug is because stat calculations will undergo a hyper training loop even after battle, despite the existence of an unused .not_hyper_trained label. Setting up a jr to .not_hyper_trained based on if the relevant bit in b is set should fix this, but for posterity's sake I'll post a bug report here.

As a side note, this rlca-jr c method for hyper training could mean that hyper training may not work as intended if the relevant bit is _not_ set for the Pokemon (i.e. you're hyper training Defense with DefEV = 212, or 11010100b, note that bit 5 is not set) but since I'm not as familiar with how hyper training works in this game or if it's even implemented yet I'll just leave it at this.

**Comment by FredrIQ** [comment]
https://github.com/Rangi42/polishedcrystal/commit/37612986e2e86e405990782d43fad63d9e7f4737

b is, or at least was at the point of that commit, either 1 or 0. The intention was to append Hyper Training bits to b as well once I got around to implementing it -- I was just going to use one of the unused OT name bits for it since it allocates 11 bytes but only use 8 (7 + terminator).

Has this changed since?
