### ISSUE TITLE
Roaming encounters while Surfing glitch

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#399]
Polished S: "While Surfing on a route where Raikou or Entei can roam on, occasionally a glitchy version of their battle theme will play during a Surfing encounter, but the wild Pokémon will not be one of them, but a regular encounter from the Surfing encounter table. However, the battle ends immediately in this case, before the battle menu is brought up, and will continue to do this until you leave the route and get into a battle elsewhere."

**Comment by Rangi42** [comment]
I can't replicate this so far.

**Comment by FredrIQ** [comment]
There was a couple of bugs related to roaming encounters fixed in af37014884c31adce4de84de919da3b2a10e232d. Under certain circumstances, the roaming Pokémon flag would get set for a regular encounter (anywhere, not just in grass), which is likely what caused this bug. As such, I'm marking this as fixed.
