### ISSUE TITLE
Rapid Spin does not raise Speed if it has been lowered

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#401]
Polished S: "Rapid Spin is supposed to be raising the user's Speed... it doesn't seem to work if the user's Speed has been lowered by one of the foe's moves, for example, Caterpie's String Shot."

**Comment by the-s-is-silent** [comment]
Another comment I would like to add is that the Speed boost might also be affected by the foe's Type and not just (or perhaps instead of) Speed debuff moves - I'd have to go back to be certain, but I recall one instance when an enemy Bug-type 'mon did not lower the Rapid Spin user's Speed, and Rapid Spin still didn't raise Speed after failing to KO and end the battle.

**Comment by FredrIQ** [comment]
Rapid Spin, like Metal Claw, will not raise Speed if the opponent fainted. Is this behaviour incorrect?

**Comment by SadisticMystic** [comment]
Official behavior is that damaging moves that boost your own stats (Metal Claw, Flame Charge, and now Rapid Spin) still have the opportunity to do so on hits that KO.

Rapid Spin is supposed to leave the hazards up if the user somehow faints (such as by running into a Rocky Helmet), though the native stat boost is checked before any of that. The full sequence in this case should go Rapid Spin -> damage -> user gets a speed boost (which will be inconsequential) -> check for Rocky Helmet damage -> process fainting -> check if the user hasn't fainted yet, and only clear hazards if they haven't.

**Comment by FredrIQ** [comment]
"raisestathit" (Metal Claw, Steel Wing, Ancient Power and Rapid Spin) has now been moved earlier in the move sequence, right after the type effectiveness message.
