### ISSUE TITLE
Status effect moves do not display move used

### ISSUE THREAD

**Issue by pootinanny** [Rangi42/polishedcrystal#535]
When you or the opponent use moves like stringshot or growth, only the move's effect text displays.

In either scenarios it does not display the "[Pokemon] uses [move]" text.

**Comment by itsdarsh** [comment]
A few things I need for background:
1. What text speed are you using?
2. Do you have battle animations on or off?

**Comment by itsdarsh** [comment]
This issue is pretty common when people have text speed at instant and since there has been no reply and no other leads on what this could be, I'm gonna assume that's the case. We may want to discuss implementing some small delay for instant text that scrolls automatically, but that's a separate issue.
