### ISSUE TITLE
Load more overworld graphics at once into OB $0:60-7F

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#554]
Emotes, rustling grass, boulder dust, Cut/Fly leaves, etc, generally load into $0:7C-7F or $0:80-8F, with grass limited to outdoors and dust limited to dungeons. The $0:60-7B area is unused, so more graphics could stay permanently available.

![image](https://user-images.githubusercontent.com/35663410/88612873-2b481600-d05a-11ea-8a7d-ff81cb4ea7d1.png)

**Comment by Kroc** [comment]
You could use these as buffer space for drawing variable-width fonts, if I'm understanding this correctly

**Comment by CiriousJoker** [comment]
> You could use these as buffer space for drawing variable-width fonts, if I'm understanding this correctly

From an aesthetics perspective I don't think this looks good. I would prefer if the space was used for something else. A different font seems weird, but maybe I'm alone with that opinion

**Comment by Kroc** [comment]
It doesn't have to be about font, per se, but the fact that you can print *anything*, rather than being limited to the number of characters you choose to fit into VRAM. The text can have symbols, bold, italic, colour etc. because you'd only be limited by ROM space (instead of VRAM), and the chosen text-encoding scheme.

**Comment by CiriousJoker** [comment]
Good point!
