### ISSUE TITLE
FAQ page Improvements & Add-ons

### ISSUE THREAD

**Issue by FranktheMute** [Rangi42/polishedcrystal#557]
This issue is intended for any improvements that would be nice to have in the FAQ page of the github. I think there are a couple more users with ideas or proposals to include, which is why I titled it in a general way. **Feel free to aggregate any of those to this post.**
My contribution is a Type Differences Chart between faithful and modified, which is something very commonly asked with no great way to look through except searching the code and changelog right now.

| Pokémon  | Old Typing | New Typing | Reasoning |
| ------------- | ------------- | ------------- | ------------- |
| Meganium | Grass | Grass/Fairy | Insert comment? |
| Typhlosion | Fire | Fire/Ground |
| Feraligatr | Water | Water/Dark |
| Noctowl | Normal/Flying | Ghost/Flying |
| Butterfree |  Bug/Flying | Bug/Psychic |
| Ledian | Bug/Flying | Bug/Fighting |
| Ariados | Bug/Poison | Bug/Dark |
| Dunsparce | Normal | Normal/Ground |
| Ampharos | Electric | Electric/Dragon |
| Politoed | Water | Water/Grass |
| Bellossom | Grass | Grass/Fairy | 
| Yanmega | Bug/Flying | Bug/Dragon  |
| Sunflora | Grass | Grass/Fire |
| Ninetales | Fire | Fire/Ghost |
| Golduck | Water | Water/Psychic |
| Magmortar | Fire | Fire/Fighting |
| Electivire | Electric | Electric/Fighting |
| Farfetch'd | Normal/Flying | Flying/Fighting |
| Octillery | Water | Water/Fire |
| Rapidash | Fire  |  Fire/Fairy |
| Rhyperior | Ground/Rock | Steel/Rock |
| Mismagius | Ghost | Ghost/Fairy |
| Charizard | Fire/Flying | Fire/Dragon |
| Blastoise | Water | Water/Steel |

**All the pokémon that got the Fairy-typing from X/Y onwards have it here. Those are:**

| Pokémon  | Old Typing | New Typing |
| ------------- | ------------- | ------------- |
| Jigglypuff | Normal | Normal/Fairy |
| Wigglytuff | Normal | Normal/Fairy |
| Clefairy | Normal | Fairy |
| Clefable | Normal | Fairy |
| Mr. Mime | Psychic | Psychic/Fairy |
| Togepi | Normal | Fairy |
| Togetic | Normal/Flying | Fairy/Flying |
| Marill | Water | Water/Fairy |
| Azumarill | Water | Water/Fairy |
| Snubbull | Normal | Fairy |
| Granbull | Normal | Fairy |

Note 1: It's up to Rangi if she wants to include the 'reasoning' tab or not. Personally I like it a lot and could be used to justify those changes that exist solely to have more typing variety (ie. dragon, ghost) or just to have some cool trivia (like ampharos' japanese name being a dragon pun, or some pokemon having the typings of their Mega-Evolutions)
Note 2: I can also type up a small chart indicating the new Forms - like the Pikachus, Armored Mewtwo, Alolan/Galarian. If I do, I plan to add a little disclaimer thing about spoilers, or we can just not have that and let it be a surprise for the players. It's up for you to decide.

**Comment by earthoul** [comment]
I'd like either FEATURES or FAQ to list the move merger with some renaming and special move-animation handling. I've added a preliminary list to [the community guide at the wiki](https://github.com/Rangi42/polishedcrystal/wiki/Community-Guide#move-merging-and-renaming-in-pc), but the official docs would suit it better. (As in this case, it'd be great for the com guide to have sth first and then for the official docs to add it and verify it officially.)

The list will look like:

| Move           | Renamed from | Merged with          | Animation                                                                                 |
|----------------|--------------|----------------------|-------------------------------------------------------------------------------------------|
| Defense Curl   | ---          | Harden, Withdraw     |                                                                                           |
| *Fury Strikes* | Fury Swipes  | Fury Attack          |                                                                                           |
| *Fresh Snack*  | Soft-Boiled  | Milk Drink           |                                                                                           |
| *HealingLight* | Morning Sun  | Synthesis, Moonlight | Synthesis's if the user is Grass type;<br>Moonlight's if it's night;<br>Morning Sun's otherwise |

Maybe I'm missing some, though.

**Comment by walkawayy** [comment]
This isn't included in the official documentation, but the [wiki](https://github.com/Rangi42/polishedcrystal/wiki) now has this info.

The [modifications](https://github.com/Rangi42/polishedcrystal/wiki/Modifications) page details changes to stats, types, abilities, moves, and species availability.

**Comment by FredrIQ** [comment]
The wiki should suffice for this.
