### ISSUE TITLE
Using variant forms for different species

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#566]
Considering how feasible this would be, and which engine features still rely on one-byte Pokémon IDs with no awareness of variant forms.

- **cries:** would complicate `OBJECTTYPE_POKEMON`; maybe treat that one specially as a high bit mask along with the form? and still use a jumptable for the rest
- **names:** `GetPokemonName` is called in many places, including `pokenamemem`
- **Pokédex entries:** also complicated by some forms not needing their own entries, like variant Magikarps
- maybe others

**Comment by FredrIQ** [comment]
I've started tentatively implementing 9bit on a branch. This is what I have in mind for implementation:

* Use the unused extspecies bit (currently IsDead in master) to refer to a second "bank" of species
* Implement a 3rd set of variant "forms" as a supergroup of the 2 other tables, for specifying even more differences (names, for instance).
* In various tables that currently specify a species (grass, trainers, etc), create a new parameter format, "dp", which takes 1-2 arguments. Argument 1 is a 9bit species. This is converted into a 8bit species byte and a byte with the extspecies bit set if the species is >255. The 2nd argument is optional and also allows specifying form.
* The new format could be combined as necessary with regular bytes. For example, grass encounters, instead of being in the format "db 5, RATTATA", it is "dbp 5, AMBIPOM" or "dbp 5, VULPIX, ALOLAN_FORM".

The first 2 parts are easy enough to add, what takes time is to change various places in the source that currently only specifies a 8bit species, into handling a 9bit one, such as wild encounters, trainers, etc. Trainers actually take a form byte already, but while you *could* for example claim that a trainer uses a Bulbasaur and then manually set the extspecies flag as part of a pokémon's form for species $100, it would be clearer if it took a dp-format argument.

Does this seem sensible? Or is there a better way of doing it?

**Comment by Rangi42** [comment]
I'd call it `mon_id`, like `map_id` being 2 bytes for the group+map, but otherwise that sounds okay. You could refer to pokecrystal16 for the things which would need updating that PC didn't add itself.

**Comment by FredrIQ** [comment]
The reason I wanted to add it as a "a/b/w"-style datatype is because it's very common to combine pokémon with other stuff. For example, wildmons care about level, BT cares about items, and so on. I think this:

    db 10 ; level
    mon_id DITTO
    db 10
    mon_id ABRA
    ...

would be less readable than this:

    dbp 10, DITTO
    dbp 10, ABRA

But maybe you disagree?

**Comment by Rangi42** [comment]
Sure, `dbp` then.

**Comment by itsdarsh** [comment]
This issue will be resolved as part of 9bit.
