### ISSUE TITLE
Fix off-by-one code and data for Key Items

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#578]
Key Item indexes start at 0 for Bicycle; they're not like items or Pokémon where 0 is nothing. However, some Key Item data tables have dummy zero entries (names), while others don't (descriptions, attributes, effects, icon pointers, icon palettes). And some code decrements the item ID before using it while other code doesn't. It looks like the Pack pocket specifically uses indexes that are one too high, and decrements them even with regard to tables that don't have a dummy zero entry.

**Comment by FredrIQ** [comment]
Key item handling has been refactored since this issue was posted. Was it fixed as a side effect?

**Comment by itsdarsh** [comment]
Key item indexes start at 1 for bicycle in 9bit now with 0 implicitly being NO_ITEM or CANCEL, context dependent. Since this issue no longer applies, I'll close this, albeit with the caveat that it may be presumptuous to assume there may still be areas in a code that have an off-by-one error that weren't caught in the latest refactor.

**Comment by setopleen** [comment]
>
