### ISSUE TITLE
Cutting grass shows a tree cut instead of the grass cut animation

### ISSUE THREAD

**Issue by nephitejnf** [Rangi42/polishedcrystal#596]
I was cutting grass front of Yellow  Forest on Route 48. I tested with other areas and got the same behavior. 

https://clips.twitch.tv/TsundereJollyIguanaRitzMitz-XdOz6awLoFd7CJie

**Comment by itsdarsh** [comment]
`wBuffer6` stores the animation type for cut ($0 for cutting trees, $1 for cutting grass) but before it's read for the animation is overwritten with the index # of the mon using cut. Since an `and 1` check is used to determine with animation to play, if the mon has an even index number (ie, Skarmory at $E2) then $E2 & $1 = $0 so the tree cut animation plays instead. There's really no reason to use `wBuffer6` for more than figuring out whether to run the tree or grass script, anyway, and that happens before `wBuffer6` gets overwritten.
