### ISSUE TITLE
[QUESTION] How do you auto-compile nightly builds?

### ISSUE THREAD

**Issue by FieryMewtwo** [Rangi42/polishedcrystal#625]

**Comment by FieryMewtwo** [comment]
If this is not the appropriate section to ask this in, please tell me.

**Comment by FieryMewtwo** [comment]
Okay, here's my new issue:

When I fork the repo, modify credits.md, and run the workflow, it fails like so:

![image](https://user-images.githubusercontent.com/77066742/114881892-68635c80-9dd1-11eb-804a-4773952ac8b2.png)

**Comment by FieryMewtwo** [comment]
How do I fix this?

**Comment by itsdarsh** [comment]
Please just ask about things like this in the Discord in the future instead of opening up a github issue on the topic. The reason it fails is because there is no older release for it to delete. Comment out lines 45-51 of https://github.com/Rangi42/polishedcrystal/blob/master/.github/workflows/main.yml#L45 and try again. If you have further problems, ask them in the #questions chat on the discord. Thanks.
