### ISSUE TITLE
Lugia is unobtainable

### ISSUE THREAD

**Issue by 03bgood** [Rangi42/polishedcrystal#640]
The Silver Wing doesn't appear in Victory Road and I have all 3 legendary birds; Articuno, Zapdoes, and Moltres. What do I do?

**Comment by Salamandar73** [comment]
Hi, 
For those little questions, don't hesitate to come in the Discord server and ask directly there. It's not a code issue.
Invitation link: https://discord.gg/fvNWsepk

Once you have caught all the 3 legendary birds, you need to visit and battle Lawrence at the Shrine, North-East of Shamouti Islands, after the Noisy Forest. The islands are accessible with ferries from Vermillion city.

**Comment by rofl0r** [comment]
i'm having the same issue (in 3.1.1) and i'm pretty sure that i battled lawrence at the shamouti shrine, yet i don't have the silver wing in my key items. now he's gone and nowhere to be found (i extensively explored all locations that feature the string lawrence (case insensitive) found by grepping asm sources.

i caught the alternative forms of the 3 legendary birds at the tree using the lures, but i'm missing the regular form of moltres. the pokedex is complete apart from lugia and i'd like to finish it before facing the pokemon league for the second time and becoming champion again. 

unfortunately i cant ask for help in discord as it now requires an account and registration doesn't accept my email address, so i'd be very grateful for any pointers.

**Comment by rofl0r** [comment]
ok, it appears the rubberducking worked, i figured i'd look where i can get the "plain" moltres and grepping the sources it turned out that it lives in the level -2 of cinnabar volcano, which i previously never found. after solving the labyrinth and finding moltres, lawrence appeared and invited me to shamouti island shrine where i battled him (again?) and finally got the silver wing.
