### ISSUE TITLE
Maylene's Magmortar!

### ISSUE THREAD

**Issue by x127x** [Rangi42/polishedcrystal#643]
At the restaurant in Celadon if you try to battle Maylene and she sends her Magmortar the game crashes!
![polished-crystal-3 0 0-b-2017-07-07_1623893076526](https://user-images.githubusercontent.com/86032456/122325553-32417680-cf01-11eb-8d51-49505f3c25c4.png)

**Comment by itsdarsh** [comment]
Given the appearance of the error screen, this is on a very old commit. We started using crash codes back in March of last year, and if you're not playing on monochrome then we haven't used a black and white error screen since October 2017. If your build is more recent than October 2019 you can try patching the save, otherwise this has likely already been patched in a newer build.

**Comment by x127x** [comment]
Thanks!--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 17/06/21, 10:26 Darsh ***@***.***> wrote:

   
  Given the appearance of the error screen, this is on a very old commit. We started using crash codes back in March of last year, and if you're not playing on monochrome then we haven't used a black and white error screen since October 2017. If your build is more recent than October 2019 you can try patching the save, otherwise this has likely already been patched in a newer build.
