### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by SOH10001** [Rangi42/polishedcrystal#963]
Came frequently crashes, always producing the following error:

Error: 000

rst 0

**Comment by FredrIQ** [comment]
What emulator are you using?

**Comment by SOH10001** [comment]
mGBA

**Comment by SOH10001** [comment]
Ran into another problem:

On the elite four the game kept crashing so frequently that I had to use a save state to save in between trainers (I chose perfect stats mode so the game is considerably more difficult!) - now that I used a save state, the game will not save via the built in save feature.

**Comment by FredrIQ** [comment]
Can you tell me the following?

* Game version. If this is 3.0.0, the filename of the rom should clarify the exact version.
* mgba version
* What happens if you try to use in-game save exactly?

The problems you describe are ones I've never seen anyone else report beforehand, and sound more akin to that of an incompatible emulator, but that should not be the case unless your mgba version is *supremely* outdated.

**Comment by SOH10001** [comment]
Just realized I was on 0.5 (*facepalm*)

Now, however, I don't know how to get my save file to open on 0.10.

**Comment by FredrIQ** [comment]
Update your emulator. Someone might be able to help you get your save working on 0.10, I cannot.
