### ISSUE TITLE
Is there a way to edit my game save?

### ISSUE THREAD

**Issue by moneydude242** [Rangi42/polishedcrystal#981]
Ok, this is kinda a dumb question written by a lazy person, but I would like to know if there is a way to edit my game saves without using something like GameShark or anything like that. In other words, just a way to edit the raw save files. I've already tried a couple of programs, but all programs say the file is "corrupted". 

(btw, I'm just trying to get myself inf rare candies because I just want to see the new things without having to dedicate too much time)

**Comment by FredrIQ** [comment]
You can't edit a Polished save with a regular Crystal save editor...

**Comment by moneydude242** [comment]
well then.... I probably can't do that since I am completely new to this stuff... However, I will research online when I have free time and try to do it! Thanks for your help!

**Comment by ciriousjoker** [comment]
@moneydude242 Keep in mind it's probably easier to use a cheat finder tool like the debug view in mgba. You search for a value, for example 2 because you currently have 2 rare candies. Then you save a snapshot, use the rare candy and filter down to values that now contain 2. You can restore save states to narrow down the search further and further. At some point you will probably just have to edit each value one after the other, check if it leads to success and remember which one lead to success 

This generally works better with stuff like your HP bar or PP.
